In [1]:
import pandas as pd
import numpy as np

In [21]:
team_stats = pd.read_csv("/Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/team_stats.csv")

In [20]:
team_stats

,ManyStats,First Downs,Fourth Down Conv.,Fumbles-Lost,Net Pass Yards,Penalties-Yards,Rush-Yds-TDs,Sacked-Yards,Third Down Conv.,Time of Possession,Total Yards,Turnovers,team_name,date,Completion,Attempts,Yards,Touchdowns,Interceptions
0,23-43-291-1-3,19,1-4,2-0,283,8-81,25-106-0,1-8,8-15,34:42,389,3,GNB,"Sunday Nov 6, 2022",23,43,291,1,3
1,14-26-137-2-1,19,0-2,0-0,137,7-62,31-117-0,0-0,6-11,25:18,254,1,DET,"Sunday Nov 6, 2022",14,26,137,2,1
2,15-28-154-1-1,20,3-3,2-1,127,10-91,39-211-2,4-27,3-16,36:18,338,2,PHI,"Sunday Dec 22, 2024",15,28,154,1,1
3,24-39-258-5-2,23,2-3,3-3,255,6-93,24-113-0,1-3,7-13,23:42,368,5,WAS,"Sunday Dec 22, 2024",24,39,258,5,2
4,27-41-204-2-0,23,0-0,0-0,204,5-45,27-107-1,0-0,7-16,31:21,311,0,DAL,"Sunday Nov 19, 2023",27,41,204,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,17-31-148-1-0,16,0-2,2-1,119,3-20,23-74-1,4-29,4-12,22:00,193,1,PIT,"Saturday Jan 4, 2025",17,31,148,1,0
2274,20-32-253-2-0,19,2-2,1-1,242,6-38,25-97-0,4-11,4-12,31:02,339,1,DAL,"Sunday Dec 24, 2023",20,32,253,2,0
2275,24-37-293-1-0,22,0-1,1-0,284,5-33,26-91-0,1-9,6-13,28:58,375,0,MIA,"Sunday Dec 24, 2023",24,37,293,1,0
2276,22-32-191-1-1,18,1-2,1-0,171,4-25,28-93-1,3-20,3-12,26:56,264,1,WAS,"Thursday Nov 14, 2024",22,32,191,1,1
2277,18-28-221-0-0,23,0-0,1-0,206,4-49,40-228-3,2-15,9-16,33:04,434,0,PHI,"Thursday Nov 14, 2024",18,28,221,0,0

In [22]:
team_stats = team_stats.drop(columns="Unnamed: 0")
team_stats = team_stats.rename(columns={"Cmp-Att-Yd-TD-INT":"ManyStats"})
team_stats[["Completion", "Attempts", "Yards", "Touchdowns", "Interceptions"]] = team_stats.ManyStats.str.split("-", expand=True)
team_stats = team_stats.drop(columns="ManyStats")

In [23]:
team_stats

,First Downs,Fourth Down Conv.,Fumbles-Lost,Net Pass Yards,Penalties-Yards,Rush-Yds-TDs,Sacked-Yards,Third Down Conv.,Time of Possession,Total Yards,Turnovers,team_name,date,Completion,Attempts,Yards,Touchdowns,Interceptions
0,19,1-4,2-0,283,8-81,25-106-0,1-8,8-15,34:42,389,3,GNB,"Sunday Nov 6, 2022",23,43,291,1,3
1,19,0-2,0-0,137,7-62,31-117-0,0-0,6-11,25:18,254,1,DET,"Sunday Nov 6, 2022",14,26,137,2,1
2,20,3-3,2-1,127,10-91,39-211-2,4-27,3-16,36:18,338,2,PHI,"Sunday Dec 22, 2024",15,28,154,1,1
3,23,2-3,3-3,255,6-93,24-113-0,1-3,7-13,23:42,368,5,WAS,"Sunday Dec 22, 2024",24,39,258,5,2
4,23,0-0,0-0,204,5-45,27-107-1,0-0,7-16,31:21,311,0,DAL,"Sunday Nov 19, 2023",27,41,204,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,16,0-2,2-1,119,3-20,23-74-1,4-29,4-12,22:00,193,1,PIT,"Saturday Jan 4, 2025",17,31,148,1,0
2274,19,2-2,1-1,242,6-38,25-97-0,4-11,4-12,31:02,339,1,DAL,"Sunday Dec 24, 2023",20,32,253,2,0
2275,22,0-1,1-0,284,5-33,26-91-0,1-9,6-13,28:58,375,0,MIA,"Sunday Dec 24, 2023",24,37,293,1,0
2276,18,1-2,1-0,171,4-25,28-93-1,3-20,3-12,26:56,264,1,WAS,"Thursday Nov 14, 2024",22,32,191,1,1
2277,23,0-0,1-0,206,4-49,40-228-3,2-15,9-16,33:04,434,0,PHI,"Thursday Nov 14, 2024",18,28,221,0,0

In [25]:
team_stats[["Success4thDown", "Failed4thDown"]] = team_stats.'Fourth Down Conv.'.str.split("-", expand=True)

SyntaxError: invalid syntax (787633686.py, line 1)