In [76]:
import pandas as pd
import numpy as np

In [105]:
team_stats = pd.read_csv('/Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/Datasets/team_stats.csv')

In [106]:
team_stats = team_stats.drop(columns='Unnamed: 0')
team_stats = team_stats.rename(columns={'Cmp-Att-Yd-TD-INT':'ManyStats'})
team_stats[['Completion', 'Attempts', 'Yards', 'Touchdowns', 'Interceptions']] = team_stats.ManyStats.str.split('-', expand=True)
team_stats = team_stats.drop(columns='ManyStats')

In [107]:
team_stats.columns = team_stats.columns.str.replace(' ', '_')
team_stats.columns = team_stats.columns.str.replace('.', '_')
team_stats.columns = team_stats.columns.str.replace('-', '_')

In [108]:
team_stats

,First_Downs,Fourth_Down_Conv_,Fumbles_Lost,Net_Pass_Yards,Penalties_Yards,Rush_Yds_TDs,Sacked_Yards,Third_Down_Conv_,Time_of_Possession,Total_Yards,Turnovers,team_name,date,Completion,Attempts,Yards,Touchdowns,Interceptions
0,19,1-4,2-0,283,8-81,25-106-0,1-8,8-15,34:42,389,3,GNB,"Sunday Nov 6, 2022",23,43,291,1,3
1,19,0-2,0-0,137,7-62,31-117-0,0-0,6-11,25:18,254,1,DET,"Sunday Nov 6, 2022",14,26,137,2,1
2,20,3-3,2-1,127,10-91,39-211-2,4-27,3-16,36:18,338,2,PHI,"Sunday Dec 22, 2024",15,28,154,1,1
3,23,2-3,3-3,255,6-93,24-113-0,1-3,7-13,23:42,368,5,WAS,"Sunday Dec 22, 2024",24,39,258,5,2
4,23,0-0,0-0,204,5-45,27-107-1,0-0,7-16,31:21,311,0,DAL,"Sunday Nov 19, 2023",27,41,204,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,16,0-2,2-1,119,3-20,23-74-1,4-29,4-12,22:00,193,1,PIT,"Saturday Jan 4, 2025",17,31,148,1,0
2274,19,2-2,1-1,242,6-38,25-97-0,4-11,4-12,31:02,339,1,DAL,"Sunday Dec 24, 2023",20,32,253,2,0
2275,22,0-1,1-0,284,5-33,26-91-0,1-9,6-13,28:58,375,0,MIA,"Sunday Dec 24, 2023",24,37,293,1,0
2276,18,1-2,1-0,171,4-25,28-93-1,3-20,3-12,26:56,264,1,WAS,"Thursday Nov 14, 2024",22,32,191,1,1
2277,23,0-0,1-0,206,4-49,40-228-3,2-15,9-16,33:04,434,0,PHI,"Thursday Nov 14, 2024",18,28,221,0,0

In [109]:
team_stats[['Success4thDown', 'Failed4thDown']] = team_stats.Fourth_Down_Conv_.str.split('-', expand=True)
team_stats[['Fumbles', 'FumblesLost']] = team_stats.Fumbles_Lost.str.split('-', expand=True)
team_stats[['Penalties', 'PenaltyYards']] = team_stats.Penalties_Yards.str.split('-', expand=True)
#team_stats[['RushAttempts', 'RushYards', 'RushTDs']] = team_stats.Rush_Yds_TDs.str.split('-', expand=True)
team_stats[['Sacked', 'SackYards']] = team_stats.Sacked_Yards.str.split('-', expand=True)
team_stats[['Success3rdDown', 'Failed3rdDown']] = team_stats.Third_Down_Conv_.str.split('-', expand=True)
team_stats[['TimeMinutes', 'TimeSeconds']] = team_stats.Time_of_Possession.str.split(':', expand=True)

In [110]:
team_stats = team_stats.drop(columns={'Fourth_Down_Conv_', 'Fumbles_Lost', 'Penalties_Yards', 'Sacked_Yards', 'Third_Down_Conv_', 'Time_of_Possession'})

The delimiters are different counts becuase there is a game where a team ran for negative yards.

In [111]:
team_stats['Rush_Yds_TDs'].str.count('-').value_counts()

Rush_Yds_TDs
2    2277
3       1
Name: count, dtype: int64

In [112]:
team_stats.loc[2083]

First_Downs                       20
Net_Pass_Yards                   295
Rush_Yds_TDs                  8--1-0
Total_Yards                      294
Turnovers                          2
team_name                        NWE
date              Sunday Oct 3, 2021
Completion                        33
Attempts                          42
Yards                            320
Touchdowns                         2
Interceptions                      1
Success4thDown                     0
Failed4thDown                      0
Fumbles                            1
FumblesLost                        1
Penalties                          8
PenaltyYards                      77
Sacked                             4
SackYards                         25
Success3rdDown                     2
Failed3rdDown                      9
TimeMinutes                       26
TimeSeconds                       05
Name: 2083, dtype: object

In [113]:
team_stats.at[2083,'Rush_Yds_TDs'] = '8-neg1-0'
team_stats

,First_Downs,Net_Pass_Yards,Rush_Yds_TDs,Total_Yards,Turnovers,team_name,date,Completion,Attempts,Yards,...,Fumbles,FumblesLost,Penalties,PenaltyYards,Sacked,SackYards,Success3rdDown,Failed3rdDown,TimeMinutes,TimeSeconds
0,19,283,25-106-0,389,3,GNB,"Sunday Nov 6, 2022",23,43,291,...,2,0,8,81,1,8,8,15,34,42
1,19,137,31-117-0,254,1,DET,"Sunday Nov 6, 2022",14,26,137,...,0,0,7,62,0,0,6,11,25,18
2,20,127,39-211-2,338,2,PHI,"Sunday Dec 22, 2024",15,28,154,...,2,1,10,91,4,27,3,16,36,18
3,23,255,24-113-0,368,5,WAS,"Sunday Dec 22, 2024",24,39,258,...,3,3,6,93,1,3,7,13,23,42
4,23,204,27-107-1,311,0,DAL,"Sunday Nov 19, 2023",27,41,204,...,0,0,5,45,0,0,7,16,31,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,16,119,23-74-1,193,1,PIT,"Saturday Jan 4, 2025",17,31,148,...,2,1,3,20,4,29,4,12,22,00
2274,19,242,25-97-0,339,1,DAL,"Sunday Dec 24, 2023",20,32,253,...,1,1,6,38,4,11,4,12,31,02
2275,22,284,26-91-0,375,0,MIA,"Sunday Dec 24, 2023",24,37,293,...,1,0,5,33,1,9,6,13,28,58
2276,18,171,28-93-1,264,1,WAS,"Thursday Nov 14, 2024",22,32,191,...,1,0,4,25,3,20,3,12,26,56
2277,23,206,40-228-3,434,0,PHI,"Thursday Nov 14, 2024",18,28,221,...,1,0,4,49,2,15,9,16,33,04

In [114]:
team_stats[['RushAttempts', 'RushYards', 'RushTDs']] = team_stats.Rush_Yds_TDs.str.split('-', expand=True)
team_stats = team_stats.drop(columns='Rush_Yds_TDs')

In [115]:
team_stats

,First_Downs,Net_Pass_Yards,Total_Yards,Turnovers,team_name,date,Completion,Attempts,Yards,Touchdowns,...,PenaltyYards,Sacked,SackYards,Success3rdDown,Failed3rdDown,TimeMinutes,TimeSeconds,RushAttempts,RushYards,RushTDs
0,19,283,389,3,GNB,"Sunday Nov 6, 2022",23,43,291,1,...,81,1,8,8,15,34,42,25,106,0
1,19,137,254,1,DET,"Sunday Nov 6, 2022",14,26,137,2,...,62,0,0,6,11,25,18,31,117,0
2,20,127,338,2,PHI,"Sunday Dec 22, 2024",15,28,154,1,...,91,4,27,3,16,36,18,39,211,2
3,23,255,368,5,WAS,"Sunday Dec 22, 2024",24,39,258,5,...,93,1,3,7,13,23,42,24,113,0
4,23,204,311,0,DAL,"Sunday Nov 19, 2023",27,41,204,2,...,45,0,0,7,16,31,21,27,107,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,16,119,193,1,PIT,"Saturday Jan 4, 2025",17,31,148,1,...,20,4,29,4,12,22,00,23,74,1
2274,19,242,339,1,DAL,"Sunday Dec 24, 2023",20,32,253,2,...,38,4,11,4,12,31,02,25,97,0
2275,22,284,375,0,MIA,"Sunday Dec 24, 2023",24,37,293,1,...,33,1,9,6,13,28,58,26,91,0
2276,18,171,264,1,WAS,"Thursday Nov 14, 2024",22,32,191,1,...,25,3,20,3,12,26,56,28,93,1
2277,23,206,434,0,PHI,"Thursday Nov 14, 2024",18,28,221,0,...,49,2,15,9,16,33,04,40,228,3

In [116]:
team_stats.at[2083, "RushYards"] = -1

In [117]:
team_stats

,First_Downs,Net_Pass_Yards,Total_Yards,Turnovers,team_name,date,Completion,Attempts,Yards,Touchdowns,...,PenaltyYards,Sacked,SackYards,Success3rdDown,Failed3rdDown,TimeMinutes,TimeSeconds,RushAttempts,RushYards,RushTDs
0,19,283,389,3,GNB,"Sunday Nov 6, 2022",23,43,291,1,...,81,1,8,8,15,34,42,25,106,0
1,19,137,254,1,DET,"Sunday Nov 6, 2022",14,26,137,2,...,62,0,0,6,11,25,18,31,117,0
2,20,127,338,2,PHI,"Sunday Dec 22, 2024",15,28,154,1,...,91,4,27,3,16,36,18,39,211,2
3,23,255,368,5,WAS,"Sunday Dec 22, 2024",24,39,258,5,...,93,1,3,7,13,23,42,24,113,0
4,23,204,311,0,DAL,"Sunday Nov 19, 2023",27,41,204,2,...,45,0,0,7,16,31,21,27,107,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,16,119,193,1,PIT,"Saturday Jan 4, 2025",17,31,148,1,...,20,4,29,4,12,22,00,23,74,1
2274,19,242,339,1,DAL,"Sunday Dec 24, 2023",20,32,253,2,...,38,4,11,4,12,31,02,25,97,0
2275,22,284,375,0,MIA,"Sunday Dec 24, 2023",24,37,293,1,...,33,1,9,6,13,28,58,26,91,0
2276,18,171,264,1,WAS,"Thursday Nov 14, 2024",22,32,191,1,...,25,3,20,3,12,26,56,28,93,1
2277,23,206,434,0,PHI,"Thursday Nov 14, 2024",18,28,221,0,...,49,2,15,9,16,33,04,40,228,3

In [124]:
skip_cols = ['team_name', 'date', ]
cols_to_change = [col for col in team_stats.columns if col not in skip_cols]
team_stats[cols_to_change] = team_stats[cols_to_change].astype(int)

In [126]:
team_stats

,First_Downs,Net_Pass_Yards,Total_Yards,Turnovers,team_name,date,Completion,Attempts,Yards,Touchdowns,...,PenaltyYards,Sacked,SackYards,Success3rdDown,Failed3rdDown,TimeMinutes,TimeSeconds,RushAttempts,RushYards,RushTDs
0,19,283,389,3,GNB,"Sunday Nov 6, 2022",23,43,291,1,...,81,1,8,8,15,34,42,25,106,0
1,19,137,254,1,DET,"Sunday Nov 6, 2022",14,26,137,2,...,62,0,0,6,11,25,18,31,117,0
2,20,127,338,2,PHI,"Sunday Dec 22, 2024",15,28,154,1,...,91,4,27,3,16,36,18,39,211,2
3,23,255,368,5,WAS,"Sunday Dec 22, 2024",24,39,258,5,...,93,1,3,7,13,23,42,24,113,0
4,23,204,311,0,DAL,"Sunday Nov 19, 2023",27,41,204,2,...,45,0,0,7,16,31,21,27,107,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,16,119,193,1,PIT,"Saturday Jan 4, 2025",17,31,148,1,...,20,4,29,4,12,22,0,23,74,1
2274,19,242,339,1,DAL,"Sunday Dec 24, 2023",20,32,253,2,...,38,4,11,4,12,31,2,25,97,0
2275,22,284,375,0,MIA,"Sunday Dec 24, 2023",24,37,293,1,...,33,1,9,6,13,28,58,26,91,0
2276,18,171,264,1,WAS,"Thursday Nov 14, 2024",22,32,191,1,...,25,3,20,3,12,26,56,28,93,1
2277,23,206,434,0,PHI,"Thursday Nov 14, 2024",18,28,221,0,...,49,2,15,9,16,33,4,40,228,3

In [131]:
team_stats['CompletionPct'] = round(100 * (team_stats['Completion'] / team_stats['Attempts']), 1)
team_stats['PctYardsPass'] = round(100 * (team_stats['Yards'] / team_stats['Total_Yards']), 1)
team_stats['PctYardsRush'] = round(100 * (team_stats['RushYards'] / team_stats['Total_Yards']), 1)
team_stats['SuccessRate4thDown'] = round(
    100 * (team_stats['Success4thDown'] / (team_stats['Success4thDown'] + team_stats['Failed4thDown'])), 1)
team_stats['SuccessRate3rdDown'] = round(
    100 * (team_stats['Success3rdDown'] / (team_stats['Success3rdDown'] + team_stats['Failed3rdDown'])), 1)

In [132]:
team_stats

,First_Downs,Net_Pass_Yards,Total_Yards,Turnovers,team_name,date,Completion,Attempts,Yards,Touchdowns,...,TimeMinutes,TimeSeconds,RushAttempts,RushYards,RushTDs,CompletionPct,PctYardsPass,PctYardsRush,SuccessRate4thDown,SuccessRate3rdDown
0,19,283,389,3,GNB,"Sunday Nov 6, 2022",23,43,291,1,...,34,42,25,106,0,53.5,74.8,27.2,20.0,34.8
1,19,137,254,1,DET,"Sunday Nov 6, 2022",14,26,137,2,...,25,18,31,117,0,53.8,53.9,46.1,0.0,35.3
2,20,127,338,2,PHI,"Sunday Dec 22, 2024",15,28,154,1,...,36,18,39,211,2,53.6,45.6,62.4,50.0,15.8
3,23,255,368,5,WAS,"Sunday Dec 22, 2024",24,39,258,5,...,23,42,24,113,0,61.5,70.1,30.7,40.0,35.0
4,23,204,311,0,DAL,"Sunday Nov 19, 2023",27,41,204,2,...,31,21,27,107,1,65.9,65.6,34.4,NaN,30.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,16,119,193,1,PIT,"Saturday Jan 4, 2025",17,31,148,1,...,22,0,23,74,1,54.8,76.7,38.3,0.0,25.0
2274,19,242,339,1,DAL,"Sunday Dec 24, 2023",20,32,253,2,...,31,2,25,97,0,62.5,74.6,28.6,50.0,25.0
2275,22,284,375,0,MIA,"Sunday Dec 24, 2023",24,37,293,1,...,28,58,26,91,0,64.9,78.1,24.3,0.0,31.6
2276,18,171,264,1,WAS,"Thursday Nov 14, 2024",22,32,191,1,...,26,56,28,93,1,68.8,72.3,35.2,33.3,20.0
2277,23,206,434,0,PHI,"Thursday Nov 14, 2024",18,28,221,0,...,33,4,40,228,3,64.3,50.9,52.5,NaN,36.0