In [4]:
import pandas as pd
from io import StringIO
from bs4 import BeautifulSoup, Comment
import re
import os
from pathlib import Path

### Needed IDs
* Expected Points Summary = expected_points
* Team Stats = team_stats
* Passing, Rushing, and Receiving = player_offense
* Defense = player_defense
* Kick/Punt Return = returns
* Kicking & Punting = kicking
* Advanced Passing = passing_advanced
* Advanced Receiving = receiving_advanced
* Advanced Rushing = rushing_advanced
* Advanced Defense = defense_advanced
* Home Team Drives = home_drives
* Away Team Drives = vis_drives

#### Expected Points

In [5]:
test_game = "/Users/camsmithers/Desktop/Camalytics/CamalyticsEnv/Projects/Sports/NFL/Data/NFLGames/NFL_1/202109090tam.html"

with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

# Game Date
scorebox_meta = soup.find("div", class_="scorebox_meta")
game_date = scorebox_meta.find_all("div")[0].text.strip()

# Opponent Name
teams = soup.find_all("a", href=lambda href: href and "/teams/" in href)
team_names = list({a.text.strip() for a in teams if a.get('href').startswith("/teams/")})

home_team = team_names[-2]
away_team = team_names[3]

comment = next(c for c in soup.find_all(string=lambda text: isinstance(text, Comment)) if "expected_points" in c)

table = BeautifulSoup(comment, "html.parser").find(id="expected_points")
df = pd.read_html(StringIO(str(table)))[0]
df["date"]= game_date
df["home_team"] = home_team
df["away_team"] = away_team

In [ ]:
df

#### Team Stats

In [7]:
with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

# Game Date
scorebox_meta = soup.find("div", class_="scorebox_meta")
game_date = scorebox_meta.find_all("div")[0].text.strip()

comment = next(c for c in soup.find_all(
    string=lambda text: isinstance(text, Comment)) if "team_stats" in c)

table = BeautifulSoup(comment, "html.parser").find(id="team_stats")
df = pd.read_html(StringIO(str(table)))[0]
df["date"]= game_date

In [ ]:
df

In [9]:
team_one = df.columns[1]
team_two = df.columns[2]
date_value = df.iat[0, -1]

In [ ]:
pivot_dal = df.pivot(columns="Unnamed: 0", values=team_one)
pivot_dal = pivot_dal.bfill().iloc[[0]]
pivot_dal

In [ ]:
pivot_tam = df.pivot(columns="Unnamed: 0", values=team_two)
pivot_tam = pivot_tam.bfill().iloc[[0]]
pivot_tam

#### Player Offense

In [ ]:
with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

tables = soup.find_all(id="player_offense")

for table in tables:
    table_html = str(table)
    df = pd.read_html(StringIO(table_html))[0]
    df["date"] = game_date

df

#### Player Defense

In [20]:
with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

# Game Date
scorebox_meta = soup.find("div", class_="scorebox_meta")
game_date = scorebox_meta.find_all("div")[0].text.strip()

comment = next(c for c in soup.find_all(
    string=lambda text: isinstance(text, Comment)) if "player_defense" in c)

table = BeautifulSoup(comment, "html.parser").find(id="player_defense")
df = pd.read_html(StringIO(str(table)))[0]
df["date"]= game_date

In [21]:
df

       Unnamed: 0_level_0 Unnamed: 1_level_0  Def Interceptions  \
                   Player                 Tm                Int
0           Jourdan Lewis                DAL                  1
1            Trevon Diggs                DAL                  1
2           Anthony Brown                DAL                  0
3           Jayron Kearse                DAL                  0
4           Micah Parsons                DAL                  0
5              Keanu Neal                DAL                  0
6       DeMarcus Lawrence                DAL                  0
7            Jaylon Smith                DAL                  0
8   Dorance Armstrong Jr.                DAL                  0
9           Tarell Basham                DAL                  0
10         Damontae Kazee                DAL                  0
11            Brent Urban                DAL                  0
12   Leighton Vander Esch                DAL                  0
13          Corey Clement                DAL                  0
14          Randy Gregory                DAL                  0
15         Osa Odighizuwa                DAL                  0
16         Carlos Watkins                DAL                  0
17     Cedrick Wilson Jr.                DAL                  0
18           Dak Prescott                DAL                  0
19         Donovan Wilson                DAL                  0
20                    NaN                NaN  Def Interceptions
21                 Player                 Tm                Int
22          Carlton Davis                TAM                  1
23        Shaquil Barrett                TAM                  0
24          Lavonte David                TAM                  0
25            Devin White                TAM                  0
26             Jamel Dean                TAM                  0
27   Antoine Winfield Jr.                TAM                  0
28          Ross Cockrell                TAM                  0
29      Jason Pierre-Paul                TAM                  0
30           Mike Edwards                TAM                  0
31           Andrew Adams                TAM                  0
32    Sean Murphy-Bunting                TAM                  0
33     Joe Tryon-Shoyinka                TAM                  0
34       William Gholston                TAM                  0
35             Ali Marpet                TAM                  0
36         Steve McLendon                TAM                  0
37           Kevin Minter                TAM                  0
38    Rakeem Nunez-Roches                TAM                  0
39           Grant Stuard                TAM                  0
40          Ndamukong Suh                TAM                  0

                                                             \
                  Yds                 TD                Lng
0                  66                  0                 66
1                   0                  0                  0
2                   0                  0                  0
3                   0                  0                  0
4                   0                  0                  0
5                   0                  0                  0
6                   0                  0                  0
7                   0                  0                  0
8                   0                  0                  0
9                   0                  0                  0
10                  0                  0                  0
11                  0                  0                  0
12                  0                  0                  0
13                  0                  0                  0
14                  0                  0                  0
15                  0                  0                  0
16                  0                  0                  0
17                  0                  0                  0
18                  0                  0                  0
19                  0                  0                  0
20  Def Interceptions  Def Interceptions  Def Interceptions
21                Yds                 TD                Lng
22                 25                  0                 25
23                  0                  0                  0
24                  0                  0                  0
25                  0                  0                  0
26                  0                  0                  0
27                  0                  0                  0
28                  0                  0                  0
29                  0                  0                  0
30                  0                  0                  0
31                  0                  0                  0
32                  0                  0                  0
33                  0                  0                  0
34                  0                  0                  0
35                  0                  0                  0
36                  0                  0                  0
37                  0                  0                  0
38                  0                  0                  0
39                  0                  0                  0
40                  0                  0                  0

                      Unnamed: 7_level_0  Tackles                             \
                   PD                 Sk     Comb     Solo      Ast      TFL
0                   2                0.0        2        0        2        0
1                   2                0.0        1        1        0        0
2                   0                0.0       11        6        5        0
3                   0                0.0       10        5        5        0
4                   1                0.0        7        3        4        0
5                   0                0.0        6        3        3        0
6                   0                0.0        5        4        1        0
7                   0                0.0        4        2        2        0
8                   0                0.0        2        0        2        0
9                   0                0.0        2        0        2        0
10                  1                0.0        2        2        0        0
11                  0                0.0        2        0        2        0
12                  0                0.0        2        2        0        0
13                  0                0.0        1        1        0        0
14                  0                0.0        1        0        1        0
15                  0                0.0        1        0        1        0
16                  0                0.0        1        1        0        0
17                  0                0.0        1        1        0        0
18                  0                0.0        0        0        0        0
19                  0                0.0        0        0        0        0
20  Def Interceptions                NaN  Tackles  Tackles  Tackles  Tackles
21                 PD                 Sk     Comb     Solo      Ast      TFL
22                  3                0.0        2        2        0        0
23                  0                1.0        4        3        1        1
24                  1                0.0       11        5        6        0
25                  0                0.0       10        8        2        0
26                  1                0.0        9        4        5        0
27                  0                0.0        8        5        3        0
28                  0                0.0        6        4        2        0
29                  0                0.0        6        3        3        0
30                  0                0.0        4        2        2        0
31                  0                0.0        3        3        0        1
32                  0                0.0        2        1        1        0
33                  0                0.0        2        1        1        0
34                  0                0.0        1        0        1        0
35                  0                0.0        1        1        0        0
36                  0                0.0        1        1        0        0
37                  0                0.0        1        0        1        0
38                  0                0.0        1        0        1        0
39                  0                0.0        1        1        0        0
40                  0                0.0        1        0        1        0

             Fumbles                                             date
     QBHits       FR      Yds       TD       FF
0         0        1       10        0        0  Thursday Sep 9, 2021
1         0        0        0        0        0  Thursday Sep 9, 2021
2         0        0        0        0        0  Thursday Sep 9, 2021
3         0        0        0        0        0  Thursday Sep 9, 2021
4         1        0        0        0        0  Thursday Sep 9, 2021
5         0        0        0        0        0  Thursday Sep 9, 2021
6         0        0        0        0        1  Thursday Sep 9, 2021
7         0        0        0        0        0  Thursday Sep 9, 2021
8         0        0        0        0        0  Thursday Sep 9, 2021
9         0        0        0        0        0  Thursday Sep 9, 2021
10        0        0        0        0        1  Thursday Sep 9, 2021
11        0        0        0        0        0  Thursday Sep 9, 2021
12        0        0        0        0        0  Thursday Sep 9, 2021
13        0        0        0        0        0  Thursday Sep 9, 2021
14        0        1        0        0        0  Thursday Sep 9, 2021
15        0        0        0        0        0  Thursday Sep 9, 2021
16        0        0        0        0        0  Thursday Sep 9, 2021
17        0        0        0        0        0  Thursday Sep 9, 2021
18        0        1        0        0        0  Thursday Sep 9, 2021
19        1        0        0        0        0  Thursday Sep 9, 2021
20  Tackles  Fumbles  Fumbles  Fumbles  Fumbles  Thursday Sep 9, 2021
21   QBHits       FR      Yds       TD       FF  Thursday Sep 9, 2021
22        0        0        0        0        0  Thursday Sep 9, 2021
23        2        0        0        0        0  Thursday Sep 9, 2021
24        1        0        0        0        0  Thursday Sep 9, 2021
25        0        0        0        0        0  Thursday Sep 9, 2021
26        0        0        0        0        0  Thursday Sep 9, 2021
27        0        0        0        0        0  Thursday Sep 9, 2021
28        0        0        0        0        0  Thursday Sep 9, 2021
29        0        0        0        0        0  Thursday Sep 9, 2021
30        0        0        0        0        0  Thursday Sep 9, 2021
31        1        0        0        0        0  Thursday Sep 9, 2021
32        0        0        0        0        0  Thursday Sep 9, 2021
33        1        0        0        0        0  Thursday Sep 9, 2021
34        0        0        0        0        0  Thursday Sep 9, 2021
35        0        0        0        0        0  Thursday Sep 9, 2021
36        0        0        0        0        0  Thursday Sep 9, 2021
37        0        0        0        0        0  Thursday Sep 9, 2021
38        1        0        0        0        0  Thursday Sep 9, 2021
39        0        0        0        0        0  Thursday Sep 9, 2021
40        1        0        0        0        0  Thursday Sep 9, 2021

#### Returns

In [22]:
with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

# Game Date
scorebox_meta = soup.find("div", class_="scorebox_meta")
game_date = scorebox_meta.find_all("div")[0].text.strip()

comment = next(c for c in soup.find_all(
    string=lambda text: isinstance(text, Comment)) if "returns" in c)

table = BeautifulSoup(comment, "html.parser").find(id="returns")
df = pd.read_html(StringIO(str(table)))[0]
df["date"]= game_date

In [23]:
df

   Unnamed: 0_level_0 Unnamed: 1_level_0  Kick Returns                \
               Player                 Tm            Rt           Yds
0         CeeDee Lamb                DAL             0             0
1  Cedrick Wilson Jr.                DAL             0             0
2                 NaN                NaN  Kick Returns  Kick Returns
3              Player                 Tm            Rt           Yds
4      Jaydon Mickens                TAM             3            92

                                             Punt Returns                \
           Y/Rt            TD           Lng           Ret           Yds
0           NaN             0             0             1            12
1           NaN             0             0             1             2
2  Kick Returns  Kick Returns  Kick Returns  Punt Returns  Punt Returns
3          Y/Rt            TD           Lng           Ret           Yds
4          30.7             0            41             2            21

                                                             date
            Y/R            TD           Lng
0          12.0             0            12  Thursday Sep 9, 2021
1           2.0             0             2  Thursday Sep 9, 2021
2  Punt Returns  Punt Returns  Punt Returns  Thursday Sep 9, 2021
3           Y/R            TD           Lng  Thursday Sep 9, 2021
4          10.5             0             7  Thursday Sep 9, 2021

#### Kicking

In [27]:
with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

# Game Date
scorebox_meta = soup.find("div", class_="scorebox_meta")
game_date = scorebox_meta.find_all("div")[0].text.strip()

comment = next(c for c in soup.find_all(
    string=lambda text: isinstance(text, Comment)) if "kicking" in c)

table = BeautifulSoup(comment, "html.parser").find(id="kicking")
df = pd.read_html(StringIO(str(table)))[0]
df["date"]= game_date

ValueError: No tables found

#### Passing Advanced

In [28]:
with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

# Game Date
scorebox_meta = soup.find("div", class_="scorebox_meta")
game_date = scorebox_meta.find_all("div")[0].text.strip()

comment = next(c for c in soup.find_all(
    string=lambda text: isinstance(text, Comment)) if "passing_advanced" in c)

table = BeautifulSoup(comment, "html.parser").find(id="passing_advanced")
df = pd.read_html(StringIO(str(table)))[0]
df["date"]= game_date

In [29]:
df

,Player,Tm,Cmp,Att,Yds,1D,1D%,IAY,IAY/PA,CAY,...,Bad%,Sk,Bltz,Hrry,Hits,Prss,Prss%,Scrm,Yds/Scr,date
0,Dak Prescott,DAL,42,58,403,21,35.6,385,6.6,205,...,15.8%,1,32,2,6,9,14.5%,3,3.3,"Thursday Sep 9, 2021"
1,Player,Tm,Cmp,Att,Yds,1D,1D%,IAY,IAY/PA,CAY,...,Bad%,Sk,Bltz,Hrry,Hits,Prss,Prss%,Scrm,Yds/Scr,"Thursday Sep 9, 2021"
2,Tom Brady,TAM,32,50,379,22,44.0,454,9.1,203,...,14.9%,0,11,1,2,3,6.0%,0,NaN,"Thursday Sep 9, 2021"

#### Receiving Advanced

In [30]:
with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

# Game Date
scorebox_meta = soup.find("div", class_="scorebox_meta")
game_date = scorebox_meta.find_all("div")[0].text.strip()

comment = next(c for c in soup.find_all(
    string=lambda text: isinstance(text, Comment)) if "receiving_advanced" in c)

table = BeautifulSoup(comment, "html.parser").find(id="receiving_advanced")
df = pd.read_html(StringIO(str(table)))[0]
df["date"]= game_date

In [31]:
df

,Player,Tm,Tgt,Rec,Yds,TD,1D,YBC,YBC/R,YAC,YAC/R,ADOT,BrkTkl,Rec/Br,Drop,Drop%,Int,Rat,date
0,Amari Cooper,DAL,17,13,139,2,8,110,8.5,29,2.2,7.5,0,NaN,0,0.0,0,139.1,"Thursday Sep 9, 2021"
1,CeeDee Lamb,DAL,15,7,104,1,5,41,5.9,63,9.0,10.6,0,NaN,2,13.3,1,64.3,"Thursday Sep 9, 2021"
2,Dalton Schultz,DAL,6,6,45,0,3,14,2.3,31,5.2,2.3,2,3.0,0,0.0,0,97.9,"Thursday Sep 9, 2021"
3,Michael Gallup,DAL,7,4,36,0,3,10,2.5,26,6.5,6.0,1,4.0,0,0.0,0,71.1,"Thursday Sep 9, 2021"
4,Tony Pollard,DAL,4,4,29,0,1,-9,-2.3,38,9.5,-2.3,0,NaN,0,0.0,0,96.9,"Thursday Sep 9, 2021"
5,Blake Jarwin,DAL,3,3,20,0,NaN,15,5.0,5,1.7,5.0,0,NaN,0,0.0,0,94.4,"Thursday Sep 9, 2021"
6,Cedrick Wilson Jr.,DAL,3,3,24,0,1,24,8.0,0,0.0,8.0,0,NaN,0,0.0,0,100.0,"Thursday Sep 9, 2021"
7,Ezekiel Elliott,DAL,2,2,6,0,0,0,0.0,6,3.0,0.0,0,NaN,0,0.0,0,79.2,"Thursday Sep 9, 2021"
8,Player,Tm,Tgt,Rec,Yds,TD,1D,YBC,YBC/R,YAC,YAC/R,ADOT,BrkTkl,Rec/Br,Drop,Drop%,Int,Rat,"Thursday Sep 9, 2021"
9,Chris Godwin,TAM,13,9,105,1,7,47,5.2,58,6.4,8.5,2,4.5,2,15.4,0,119.1,"Thursday Sep 9, 2021"
10,Rob Gronkowski,TAM,8,8,90,2,5,53,6.6,37,4.6,6.6,0,NaN,0,0.0,0,153.1,"Thursday Sep 9, 2021"
11,Antonio Brown,TAM,7,5,121,1,4,94,18.8,27,5.4,20.6,0,NaN,0,0.0,0,153.3,"Thursday Sep 9, 2021"
12,Leonard Fournette,TAM,7,5,27,0,3,-8,-1.6,35,7.0,-0.6,0,NaN,1,14.3,1,38.1,"Thursday Sep 9, 2021"
13,Mike Evans,TAM,6,3,24,0,2,18,6.0,6,2.0,7.7,0,NaN,0,0.0,0,60.4,"Thursday Sep 9, 2021"
14,Giovani Bernard,TAM,3,2,12,0,1,-1,-0.5,13,6.5,6.3,0,NaN,0,0.0,0,74.3,"Thursday Sep 9, 2021"
15,Tyler Johnson,TAM,1,0,0,0,NaN,0,NaN,0,NaN,10.0,0,NaN,0,0.0,0,39.6,"Thursday Sep 9, 2021"

#### Rushing Advanced

In [32]:
with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

# Game Date
scorebox_meta = soup.find("div", class_="scorebox_meta")
game_date = scorebox_meta.find_all("div")[0].text.strip()

comment = next(c for c in soup.find_all(
    string=lambda text: isinstance(text, Comment)) if "rushing_advanced" in c)

table = BeautifulSoup(comment, "html.parser").find(id="rushing_advanced")
df = pd.read_html(StringIO(str(table)))[0]
df["date"]= game_date

In [33]:
df

,Player,Tm,Att,Yds,TD,1D,YBC,YBC/Att,YAC,YAC/Att,BrkTkl,Att/Br,date
0,Ezekiel Elliott,DAL,11,33,0,2,20,1.8,13,1.2,0,NaN,"Thursday Sep 9, 2021"
1,Dak Prescott,DAL,4,13,0,0,8,2.0,5,1.3,0,NaN,"Thursday Sep 9, 2021"
2,Tony Pollard,DAL,3,14,0,2,10,3.3,4,1.3,0,NaN,"Thursday Sep 9, 2021"
3,Player,Tm,Att,Yds,TD,1D,YBC,YBC/Att,YAC,YAC/Att,BrkTkl,Att/Br,"Thursday Sep 9, 2021"
4,Leonard Fournette,TAM,9,32,0,1,14,1.6,18,2.0,1,9.0,"Thursday Sep 9, 2021"
5,Ronald Jones II,TAM,4,14,0,NaN,7,1.8,7,1.8,0,NaN,"Thursday Sep 9, 2021"
6,Antonio Brown,TAM,1,6,0,0,5,5.0,1,1.0,0,NaN,"Thursday Sep 9, 2021"

#### Defense Advanced

In [34]:
with open(test_game, encoding="utf-8") as f:
    page = f.read()

soup = BeautifulSoup(page, "html.parser")

# Game Date
scorebox_meta = soup.find("div", class_="scorebox_meta")
game_date = scorebox_meta.find_all("div")[0].text.strip()

comment = next(c for c in soup.find_all(
    string=lambda text: isinstance(text, Comment)) if "defense_advanced" in c)

table = BeautifulSoup(comment, "html.parser").find(id="defense_advanced")
df = pd.read_html(StringIO(str(table)))[0]
df["date"]= game_date

In [35]:
df

,Player,Tm,Int,Tgt,Cmp,Cmp%,Yds,Yds/Cmp,Yds/Tgt,TD,...,YAC,Bltz,Hrry,QBKD,Sk,Prss,Comb,MTkl,MTkl%,date
0,Anthony Brown,DAL,0,9,8,88.9%,127,15.9,14.1,1,...,33,0,0,0,0.0,0,11,0,0.0%,"Thursday Sep 9, 2021"
1,Jourdan Lewis,DAL,1,11,6,54.5%,74,12.3,6.7,1,...,43,0,0,0,0.0,0,2,1,33.3%,"Thursday Sep 9, 2021"
2,Micah Parsons,DAL,0,7,5,71.4%,44,8.8,6.3,0,...,20,7,0,1,0.0,1,7,2,22.2%,"Thursday Sep 9, 2021"
3,Jayron Kearse,DAL,0,4,4,100.0%,33,8.3,8.3,1,...,23,1,0,0,0.0,0,10,0,0.0%,"Thursday Sep 9, 2021"
4,Jaylon Smith,DAL,0,2,2,100.0%,6,3.0,3.0,0,...,3,2,0,0,0.0,0,4,0,0.0%,"Thursday Sep 9, 2021"
5,Keanu Neal,DAL,0,2,2,100.0%,29,14.5,14.5,0,...,6,0,0,0,0.0,0,6,2,25.0%,"Thursday Sep 9, 2021"
6,Dorance Armstrong Jr.,DAL,0,1,1,100.0%,8,8.0,8.0,0,...,13,0,0,0,0.0,0,2,0,0.0%,"Thursday Sep 9, 2021"
7,Leighton Vander Esch,DAL,0,1,1,100.0%,10,10.0,10.0,0,...,13,0,0,0,0.0,0,2,0,0.0%,"Thursday Sep 9, 2021"
8,DeMarcus Lawrence,DAL,0,1,1,100.0%,11,11.0,11.0,1,...,8,0,0,0,0.0,0,5,1,16.7%,"Thursday Sep 9, 2021"
9,Trevon Diggs,DAL,1,5,1,20.0%,10,10.0,2.0,0,...,3,0,0,0,0.0,0,1,1,50.0%,"Thursday Sep 9, 2021"
10,Damontae Kazee,DAL,0,3,1,33.3%,27,27.0,9.0,0,...,11,0,0,0,0.0,0,2,0,0.0%,"Thursday Sep 9, 2021"
11,Donovan Wilson,DAL,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1,0,1,0.0,1,0,0,NaN,"Thursday Sep 9, 2021"
12,Quinton Bohanna,DAL,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,0.0,1,0,0,NaN,"Thursday Sep 9, 2021"
13,Bradlee Anae,DAL,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1,0,0,0.0,0,0,0,NaN,"Thursday Sep 9, 2021"
14,Player,Tm,Int,Tgt,Cmp,Cmp%,Yds,Yds/Cmp,Yds/Tgt,TD,...,YAC,Bltz,Hrry,QBKD,Sk,Prss,Comb,MTkl,MTkl%,"Thursday Sep 9, 2021"
15,Devin White,TAM,0,7,7,100.0%,54,7.7,7.7,0,...,24,7,0,0,0.0,0,10,2,16.7%,"Thursday Sep 9, 2021"
16,Lavonte David,TAM,0,7,6,85.7%,34,5.7,4.9,0,...,20,8,0,1,0.0,1,11,0,0.0%,"Thursday Sep 9, 2021"
17,Ross Cockrell,TAM,0,9,6,66.7%,63,10.5,7.0,1,...,11,1,0,0,0.0,0,6,0,0.0%,"Thursday Sep 9, 2021"
18,Jamel Dean,TAM,0,8,5,62.5%,61,12.2,7.6,0,...,45,0,0,0,0.0,0,9,1,10.0%,"Thursday Sep 9, 2021"
19,Carlton Davis,TAM,1,9,4,44.4%,43,10.8,4.8,0,...,14,2,0,0,0.0,0,2,3,60.0%,"Thursday Sep 9, 2021"
20,Jason Pierre-Paul,TAM,0,4,4,100.0%,18,4.5,4.5,0,...,21,3,0,0,0.0,0,6,0,0.0%,"Thursday Sep 9, 2021"
21,Sean Murphy-Bunting,TAM,0,7,4,57.1%,49,12.3,7.0,1,...,35,0,0,0,0.0,0,2,0,0.0%,"Thursday Sep 9, 2021"
22,Antoine Winfield Jr.,TAM,0,3,2,66.7%,41,20.5,13.7,0,...,5,0,0,0,0.0,0,8,0,0.0%,"Thursday Sep 9, 2021"
23,Shaquil Barrett,TAM,0,1,1,100.0%,16,16.0,16.0,0,...,19,14,1,1,1.0,3,4,0,0.0%,"Thursday Sep 9, 2021"
24,Andrew Adams,TAM,0,1,1,100.0%,14,14.0,14.0,0,...,0,3,0,1,0.0,1,3,0,0.0%,"Thursday Sep 9, 2021"
25,Mike Edwards,TAM,0,1,1,100.0%,5,5.0,5.0,0,...,4,6,0,0,0.0,0,4,0,0.0%,"Thursday Sep 9, 2021"
26,Rakeem Nunez-Roches,TAM,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1,0,1,0.0,1,1,0,0.0%,"Thursday Sep 9, 2021"
27,Ndamukong Suh,TAM,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,0,0,1,0.0,1,1,0,0.0%,"Thursday Sep 9, 2021"
28,Joe Tryon-Shoyinka,TAM,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,4,0,1,0.0,1,2,1,33.3%,"Thursday Sep 9, 2021"
29,Vita Vea,TAM,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,0.0,1,0,0,NaN,"Thursday Sep 9, 2021"
30,Bradley Pinion,TAM,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,1,0,0,0.0,0,0,0,NaN,"Thursday Sep 9, 2021"